Docksal
* Removed Port mappings from main docksal.yml - moved to docksal.local.yml
* example.docksal.local.yml
* gitignored docksal.local.yml
* added flag to `fin init` - option to destroy/reset container

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -10,8 +10,17 @@ NC='\033[0m'
 #-------- Runtime ----------
 
 # Reset containers
-echo -e "\n${yellow}Resetting containers${NC}"
-fin project reset --force
+while getopts ":r" flag; do
+  case $flag in
+    r)
+      echo -e "\n${yellow}Resetting containers${NC}"
+      fin project reset --force
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
 
 # Update Node to LTS, and use it
 if [ "$NODE_VERSION" ]; then
